model = dict(
    encoder=dict(
        type='GIN',
        num_node_emb_list=[39],
        num_edge_emb_list=[10],
        num_layers=2,
        emb_dim=256,
        readout='mean',
        JK='last',
        dropout=0.5
    ),
    subencoder=dict(
        type='GIN',
        num_node_emb_list=[39],
        num_edge_emb_list=[10],
        num_layers=5,
        emb_dim=256,
        readout='mean',
        JK='last',
        dropout=0.5,
    ),
)
drop_ratio=0.7